feat: Implement `carrier apps list` via local api request
SUSE/carrier pull request #241
Opened 2021-03-29 12:38 UTC by jimmykarily

Fixes #238 

Co-authored-by: Dimitris Karakasilis <DKarakasilis@suse.com>

2021-04-02 09:21 UTC, rohitsakala requested changes
This URL [0] needs to be updated.

[0] https://github.com/SUSE/carrier/blob/main/embedded-web-files/assets/js/applications.js#L8

2021-04-06 08:04 UTC, andreas-kupries commented on acceptance/utilities_test.go
> +	p.Stderr = os.Stdout
I believe @jimmykarily uses stdout for both intentionally

2021-04-06 08:04 UTC, andreas-kupries commented
Will fix the urls in the javascript.

2021-04-06 08:59 UTC, jimmykarily commented on acceptance/utilities_test.go
> +	p.Stderr = os.Stdout
I'm not sure Sterr is printed while running tests, not sure. We just need to make sure we will see the error.

2021-04-06 09:04 UTC, andreas-kupries commented on acceptance/utilities_test.go
> +	p.Stderr = os.Stdout
Good point. I consider this as resolved now.

2021-04-06 09:18 UTC, andreas-kupries approved these changes

2021-04-06 09:36 UTC, merged